# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/pelican
image: python:3.9-alpine

pages:
  script:
    - git submodule update --init
    - pip install pipenv
    - pipenv install --dev
    - pipenv run pelican content -vvv -o public -s pelicanconf.py
  artifacts:
    paths:
      - public/
