# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/pelican
image: python:alpine

pages:
  script:
    - pip install -r requirements.txt
    - pelican content -vvv -o output -s pelicanconf.py
  artifacts:
    paths:
      - output/
