stages:
  - deploy

default:
  image: chainguard/wolfi-base:latest

pages:
  stage: deploy
  script:
      curl -fsSL https://install.determinate.systems/nix | sh -s -- install linux --no-confirm --determinate --init none
      nix run .#zola -- build

  artifacts:
    paths:
      # This is the directory whose contents will be deployed to the GitLab Pages server.
      # GitLab Pages expects a directory with this name by default.
      - public

  rules:
    # This rule makes it so that your website is published and updated only when
    # you push to the default branch of your repository (e.g. "master" or "main").
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
