# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/pelican
image: python:3.9-alpine

pages:
  script:
    - pip install -r requirements.txt
    - pelican content -vvv -o public -s pelicanconf.py
  artifacts:
    paths:
      - public/
