# TODO: nixify
stages:
  - deploy

default:
  image: alpine

variables:
  ZOLA_VERSION:
    description: "The version of Zola used to build the site."
    value: "0.21.0"

pages:
  stage: deploy
  script:
    - |
      zola_url="https://github.com/getzola/zola/releases/download/v${ZOLA_VERSION}/zola-v${ZOLA_VERSION}-x86_64-unknown-linux-gnu.tar.gz"
      apk add --no-cache curl
      curl -Lo zola.tar.gz "$zola_url" \
      | tar -xvz
      ./zola build --base-url $CI_PAGES_URL

  artifacts:
    paths:
      # This is the directory whose contents will be deployed to the GitLab Pages server.
      # GitLab Pages expects a directory with this name by default.
      - public

  rules:
    # This rule makes it so that your website is published and updated only when
    # you push to the default branch of your repository (e.g. "master" or "main").
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
