# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/pelican
image: python:3.9-alpine

variables:
  GIT_SUBMODULE_STRATEGY: normal
  
include:
  - template: Dependency-Scanning.gitlab-ci.yml

pages:
  script:
    - pip install pipenv
    - pipenv install --dev
    - pipenv run pelican content -vvv -o public -s pelicanconf.py
  artifacts:
    paths:
      - public/
  environment:
    name: prod
    url: $CI_PAGES_URL
