sudo: false
language: python
cache: pip
python:
  - 3.9-dev
install:
  - pip install pipenv
  - pipenv install --dev
script:
  - git submodule update --init
  - pipenv run pelican content -vvv -o output -s pelicanconf.py

deploy:
  provider: pages
  fqdn: blog.kaictl.me
  local-dir: output/
  target-branch: gh-pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
