## General
base_url = "https://blog.kaictl.me"
compile_sass = false
minify_html = true
generate_feeds = true
generate_sitemap = true

theme = "anemone"

# Taxonomies
taxonomies = [
    {name = "tags", feed = true, paginate_by = 10},
]

[languages.en]
build_search_index = true
title = "blog.kaictl"
description = "Blog"

[markdown]
render_emoji = true
external_links_target_blank = true
smart_punctuation = true
highlight_code = true
highlight_theme = "gruvbox-dark"

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[link_checker]
internal_level = "warn"

# Extra
[extra]
author = "kaictl"
favicon = "favicon.ico"
list_pages = false
twitter_card = true
enable_search = true

## Navigation
header_nav = [
  { url = "/", name_en = "/home/" },
  { url = "/about", name_en = "/about/" },
  { url = "/journal", name_en = "/journal/" },
  { url = "/blog", name_en = "/blog/" }
]
